local Debugger = require("hotswitch-hs/lib/common/Debugger")
local TimeChecker = require("hotswitch-hs/lib/common/TimeChecker")
local Controller = require("hotswitch-hs/lib/controller/Controller")
local WindowModel = require("hotswitch-hs/lib/model/WindowModel")
local SettingsModel = require("hotswitch-hs/lib/model/SettingModel")
local KeyStatusModel = require("hotswitch-hs/lib/model/KeyStatusModel")
local AppWatchModel = require("hotswitch-hs/lib/model/AppWatchModel")
local PanelLayoutView = require("hotswitch-hs/lib/view/PanelLayoutView")
local HotkeyController = require("hotswitch-hs/lib/controller/HotkeyController")

local MainController = {}
MainController.new = function()
    local obj = Controller.new()

    obj.isRegistrationMode = false

    obj.windowModel = WindowModel.new()
    obj.settingModel = SettingsModel.new()
    obj.keyStatusModel = KeyStatusModel.new(obj.windowModel, obj.settingModel)
    obj.appWatchModel = AppWatchModel.new()

    obj.panelLayoutView = PanelLayoutView.new(obj.windowModel, obj.settingModel, obj.keyStatusModel)

    obj.hotkeyController = HotkeyController.new(obj)

    obj.init = function(self)
        self.hotkeyController:createHotkeys()
        self.keyStatusModel:resetAutoGeneratedKeys()
        self.windowModel:init()

        self.panelLayoutView:setClickCallback(function(position)
            self.focusWindow(self.windowModel:getCachedOrderedWindowsOrFetch()[position])
            self:finish()
        end)
    end

    obj.openOrClose = function(self)
        if self.panelLayoutView.isOpen then
            self.windowModel:focusPreviousWindowForCancel()
            self:finish()
        else
            local t = TimeChecker.new()
            self.windowModel.previousWindow = hs.window.frontmostWindow()

            -- Enable hotkeys before refresh windows,
            -- because refreshing windows is sometimes slow and take time.
            self.hotkeyController:enableHotkeys()
            self.panelLayoutView:activateHammerspoonWindow()

            self.windowModel:refreshOrderedWindows()
            self.keyStatusModel:createKeyStatuses()
            self.panelLayoutView:show()
            self.appWatchModel:watchAppliationDeactivated(function() self:finish() end)
        end
    end

    obj.clearSettings = function(self)
        self.settingModel.clear()
    end

    obj.setAutoGeneratedKeys = function(self, specifiedAutoGeneratedKeys)
        self.keyStatusModel:setSpecifiedAutoGeneratedKeys(specifiedAutoGeneratedKeys)
        self.keyStatusModel:resetAutoGeneratedKeys()
    end

    obj.enableAllSpaceWindows = function(self)
        self.windowModel:enableAllSpaceWindows()
    end

    obj.finish = function(self)
        self.panelLayoutView:hide()
        self.hotkeyController:disableHotkeys()
        self.appWatchModel:unwatchAppliationDeactivated()
    end

    return obj
end
return MainController