local Debugger = require("hotswitch-hs/lib/common/Debugger")
local MainController = require("hotswitch-hs/lib/controller/MainController")
local PreferenceModel = require("hotswitch-hs/lib/model/PreferenceModel")

local mainController = MainController.new()

return {
    togglePanel = function() mainController:togglePanel() end,
    openOrClose = function() mainController:togglePanel() end, -- Backward-compatible alias for togglePanel()
    cycleWithModifier = function(modifiers, key) mainController:cycleWithModifier(modifiers, key) end,
    commitCycle = function() mainController:commitCycle() end,
    cycleNext = function() mainController:cycleNext() end,
    cyclePrevious = function() mainController:cyclePrevious() end,
    switchToNextWindow = function() mainController:switchToNextWindow() end,
    switchToPreviousWindow = function() mainController:switchToPreviousWindow() end,
    setAutoGeneratedKeys = function(specifiedAutoGeneratedKeys)
        mainController:setAutoGeneratedKeys(specifiedAutoGeneratedKeys)
    end,
    enableAllSpaceWindows = function() mainController:enableAllSpaceWindows() end,
    enableAutoUpdate = function() mainController.checkUpdate() end,
    checkUpdateNow = function() mainController.checkUpdateNow() end,
    addJapaneseKeyboardLayoutSymbolKeys = function() mainController:addJapaneseKeyboardLayoutSymbolKeys() end,
    setPanelToAlwaysShowOnPrimaryScreen = function() mainController:setPanelToAlwaysShowOnPrimaryScreen() end,
    clearSettings = function() mainController:clearSettings() end,
    clearPreferences = function() PreferenceModel.clearPreferences() end,
    addKeyModifier = function() mainController:addKeyModifier() end,
    setLogLevel = function(logLevel)
        mainController:setLogLevel(logLevel)
    end,
}
