local Debugger = require("hotswitch-hs/lib/common/Debugger")

local MainController = require("hotswitch-hs/lib/controller/MainController")
local SettingModel = require("hotswitch-hs/lib/model/SettingModel")

local mainController = MainController.new()
local function main()
    mainController:createHotkeys()
    mainController.panelLayoutView.baseCanvasView:resetAutoGeneratedKeys()
end

local function openOrClose()
    if mainController.panelLayoutView.isOpen then
        mainController:focusWindowForCancel()
        mainController:finish()
    else
        mainController.windowModel.previousWindow = hs.window.frontmostWindow()

        -- Enable hotkeys before refresh windows,
        -- because refreshing windows is slow and take time.
        mainController:enableHotkeys()
        mainController.panelLayoutView.baseCanvasView:activateHammerspoonWindow()
        mainController.windowModel:refreshOrderedWindows()
        mainController.panelLayoutView:show()
        mainController:watchAppliationDeactivated()
    end
end

local function clearSettings()
    SettingModel.new().clear()
end

local function enableDebug()
    Debugger.setDebuggable(true)
end

-- arg: autoGeneratedKeys = {"a", "b", "c"}
local function setAutoGeneratedKeys(specifiedAutoGeneratedKeys)
    mainController.panelLayoutView.baseCanvasView:setSpecifiedAutoGeneratedKeys(specifiedAutoGeneratedKeys)
    mainController.panelLayoutView.baseCanvasView:resetAutoGeneratedKeys()
end

main()

return {
    openOrClose = openOrClose,
    clearSettings = clearSettings,
    enableDebug = enableDebug,
    setAutoGeneratedKeys = setAutoGeneratedKeys,
}