local Debugger = require("hotswitch-hs/lib/common/Debugger")
local MainController = require("hotswitch-hs/lib/controller/MainController")

local mainController = MainController.new()

return {
    openOrClose = function() mainController:openOrClose() end,
    setAutoGeneratedKeys = function(specifiedAutoGeneratedKeys) mainController:setAutoGeneratedKeys(specifiedAutoGeneratedKeys) end,
    enableAllSpaceWindows = function() mainController:enableAllSpaceWindows() end,
    enableAutoUpdate = function() mainController.checkUpdate() end,
    clearSettings = function() mainController:clearSettings() end,
    enableDebug = function() Debugger.setDebuggable(true) end,
}